import i18n from '@/lang';
export let resource = {
    "nodes":[
        {"documentation":"","id":"start","name":"Тест","properties":null,"type":"start","uname":"","user":"","model":{"id":"start","shape":"start","label":"Тест","labelCfg":{"position":"center","style":{"fontSize":12}},"width":40,"height":40,"minWidth":20,"minHeight":20,"anchorPoints":[[0.5,0],[0.5,1],[0,0.5],[1,0.5]],"shapeControl":{"controllers":[[0,0,"nwse-resize"],[0,0.5,"ew-resize"],[0,1,"nesw-resize"],[0.5,0,"ns-resize"],[0.5,1,"ns-resize"],[1,0,"nesw-resize"],[1,0.5,"ew-resize"],[1,1,"nwse-resize"]],"rotate":true},"style":{"fill":"#fdf6e7","stroke":"#fbad5a","fillOpacity":1,"lineWidth":1,"lineDash":[]},"x":402.5,"y":31,"size":[40,40]}},
        {"documentation":"","id":"apply","name":"Тест2","properties":null,"type":"task","uname":"","user":"","model":{"id":"apply","shape":"apply","label":"Тест","labelCfg":{"position":"center","style":{"fontSize":12}},"width":80,"height":40,"minWidth":20,"minHeight":20,"anchorPoints":[[0.5,0],[0.5,1],[0,0.5],[1,0.5]],"shapeControl":{"controllers":[[0,0,"nwse-resize"],[0,0.5,"ew-resize"],[0,1,"nesw-resize"],[0.5,0,"ns-resize"],[0.5,1,"ns-resize"],[1,0,"nesw-resize"],[1,0.5,"ew-resize"],[1,1,"nwse-resize"]],"rotate":true},"style":{"fill":"#e7feeb","stroke":"#9efeae","fillOpacity":1,"lineWidth":1,"lineDash":[]},"x":402.5,"y":105,"size":[80,40]}},
        {"documentation":"","id":"task_g30","name":"Тест3","properties":null,"type":"task","uname":"","user":"","model":{"id":"task_g30","shape":"task","label":"Тест","labelCfg":{"position":"center","style":{"fontSize":12}},"width":80,"height":40,"minWidth":20,"minHeight":20,"anchorPoints":[[0.5,0],[0.5,1],[0,0.5],[1,0.5]],"shapeControl":{"controllers":[[0,0,"nwse-resize"],[0,0.5,"ew-resize"],[0,1,"nesw-resize"],[0.5,0,"ns-resize"],[0.5,1,"ns-resize"],[1,0,"nesw-resize"],[1,0.5,"ew-resize"],[1,1,"nwse-resize"]],"rotate":true},"style":{"fill":"#e7f7fe","stroke":"#9ed2fe","fillOpacity":1,"lineWidth":1,"lineDash":[]},"x":402.5,"y":186,"size":[80,40]}},
        {"documentation":"","id":"exclusiveGateway_g34","name":"Тест4","properties":null,"type":"exclusiveGateway","uname":"","user":"","model":{"id":"exclusiveGateway_g34","shape":"exclusiveGateway","label":"","labelCfg":{"position":"center","style":{"fontSize":12}},"width":40,"height":40,"minWidth":20,"minHeight":20,"anchorPoints":[[0.5,0],[0.5,1],[0,0.5],[1,0.5]],"shapeControl":{"controllers":[[0,0,"nwse-resize"],[0,0.5,"ew-resize"],[0,1,"nesw-resize"],[0.5,0,"ns-resize"],[0.5,1,"ns-resize"],[1,0,"nesw-resize"],[1,0.5,"ew-resize"],[1,1,"nwse-resize"]],"rotate":true},"style":{"fill":"#e8fefa","stroke":"#1ac4c4","fillOpacity":1,"lineWidth":1,"lineDash":[]},"x":402.5,"y":275,"size":[40,40]}},
        {"documentation":"","id":"task_g38","name":"Тест5","properties":null,"type":"task","uname":"","user":"","model":{"id":"task_g38","shape":"task","label":"Тест","labelCfg":{"position":"center","style":{"fontSize":12}},"width":80,"height":40,"minWidth":20,"minHeight":20,"anchorPoints":[[0.5,0],[0.5,1],[0,0.5],[1,0.5]],"shapeControl":{"controllers":[[0,0,"nwse-resize"],[0,0.5,"ew-resize"],[0,1,"nesw-resize"],[0.5,0,"ns-resize"],[0.5,1,"ns-resize"],[1,0,"nesw-resize"],[1,0.5,"ew-resize"],[1,1,"nwse-resize"]],"rotate":true},"style":{"fill":"#e7f7fe","stroke":"#9ed2fe","fillOpacity":1,"lineWidth":1,"lineDash":[]},"x":402.5,"y":357,"size":[80,40]}},
        {"documentation":"","id":"end","name":"Тест6","properties":null,"type":"end","uname":"","user":"","model":{"id":"end","shape":"end","label":"Тест","labelCfg":{"position":"center","style":{"fontSize":12}},"width":40,"height":40,"minWidth":20,"minHeight":20,"anchorPoints":[[0.5,0],[0.5,1],[0,0.5],[1,0.5]],"shapeControl":{"controllers":[[0,0,"nwse-resize"],[0,0.5,"ew-resize"],[0,1,"nesw-resize"],[0.5,0,"ns-resize"],[0.5,1,"ns-resize"],[1,0,"nesw-resize"],[1,0.5,"ew-resize"],[1,1,"nwse-resize"]],"rotate":true},"style":{"fill":"#fce6e9","stroke":"#f46369","fillOpacity":1,"lineWidth":1,"lineDash":[]},"x":402.5,"y":455,"size":[40,40]}}],
    "lines":[
        {"conditionType":"","from":"start","id":"g46","name":"","properties":null,"to":"apply","type":"","model":{"id":"g46","source":"start","sourceAnchor":1,"target":"apply","label":"","labelCfg":{"position":"center","style":{"fontSize":16,"stroke":"#000000"}},"lineAppendWidth":20,"attrs":{"start":"start","end":"apply"},"style":{"stroke":"#999999","lineWidth":1,"lineDash":[]},"shape":"x-line","startArrow":false,"endArrow":true,"startPoint":{"x":402.5,"y":51.5,"index":1,"anchorIndex":1},"endPoint":{"x":402.5,"y":84.5,"index":1,"anchorIndex":1},"targetAnchor":1}},
        {"conditionType":"","from":"apply","id":"g47","name":"","properties":null,"to":"task_g30","type":"","model":{"id":"g47","source":"apply","sourceAnchor":3,"target":"task_g30","label":"","labelCfg":{"position":"center","style":{"fontSize":16,"stroke":"#000000"}},"lineAppendWidth":20,"attrs":{"start":"apply","end":"task_g30"},"style":{"stroke":"#999999","lineWidth":1,"lineDash":[]},"shape":"x-line","startArrow":false,"endArrow":true,"startPoint":{"x":402.5,"y":125.5,"index":3,"anchorIndex":3},"endPoint":{"x":402.5,"y":165.5,"index":1},"targetAnchor":1}},
        {"conditionType":"","from":"task_g30","id":"g48","name":"","properties":null,"to":"exclusiveGateway_g34","type":"","model":{"id":"g48","source":"task_g30","sourceAnchor":3,"target":"exclusiveGateway_g34","label":"","labelCfg":{"position":"center","style":{"fontSize":16,"stroke":"#000000"}},"lineAppendWidth":20,"attrs":{"start":"task_g30","end":"exclusiveGateway_g34"},"style":{"stroke":"#999999","lineWidth":1,"lineDash":[]},"shape":"x-line","startArrow":false,"endArrow":true,"startPoint":{"x":402.5,"y":206.5,"index":3},"endPoint":{"x":402.5,"y":254.5,"index":0},"targetAnchor":0}},
        {"conditionType":"","from":"exclusiveGateway_g34","id":"g49","name":"","properties":null,"to":"task_g38","type":"","model":{"id":"g49","source":"exclusiveGateway_g34","sourceAnchor":2,"target":"task_g38","label":"","labelCfg":{"position":"center","style":{"fontSize":16,"stroke":"#000000"}},"lineAppendWidth":20,"attrs":{"start":"exclusiveGateway_g34","end":"task_g38"},"style":{"stroke":"#999999","lineWidth":1,"lineDash":[]},"shape":"x-line","startArrow":false,"endArrow":true,"startPoint":{"x":402.5,"y":295.5,"index":2},"endPoint":{"x":402.5,"y":336.5,"index":1},"targetAnchor":1}},
        {"conditionType":"","from":"task_g38","id":"g50","name":"","properties":null,"to":"end","type":"","model":{"id":"g50","source":"task_g38","sourceAnchor":3,"target":"end","label":"","labelCfg":{"position":"center","style":{"fontSize":16,"stroke":"#000000"}},"lineAppendWidth":20,"attrs":{"start":"task_g38","end":"end"},"style":{"stroke":"#999999","lineWidth":1,"lineDash":[]},"shape":"x-line","startArrow":false,"endArrow":true,"startPoint":{"x":402.5,"y":377.5,"index":3},"endPoint":{"x":402.5,"y":434.5,"index":0},"targetAnchor":0}},
        {"conditionType":"","from":"exclusiveGateway_g34","id":"g51","name":"","properties":null,"to":"end","type":"","model":{"id":"g51","source":"exclusiveGateway_g34","sourceAnchor":3,"target":"end","label":"","labelCfg":{"position":"center","style":{"fontSize":16,"stroke":"#000000"}},"lineAppendWidth":20,"attrs":{"start":"exclusiveGateway_g34","end":"end"},"style":{"stroke":"#999999","lineWidth":1,"lineDash":[]},"shape":"x-broken","startArrow":false,"endArrow":true,"startPoint":{"x":382,"y":275,"index":3},"endPoint":{"x":382,"y":455,"index":2},"targetAnchor":2}}
    ]
}


export let distribution = {
    "nodes":[{"documentation":"","id":"start","name":"开始","properties":null,"type":"start","uname":"","user":"","model":{"id":"start","shape":"start","label":"","labelCfg":{"position":"center","style":{"fontSize":12}},"width":40,"height":40,"minWidth":20,"minHeight":20,"anchorPoints":[[0.5,0],[0.5,1],[0,0.5],[1,0.5]],"shapeControl":{"controllers":[[0,0,"nwse-resize"],[0,0.5,"ew-resize"],[0,1,"nesw-resize"],[0.5,0,"ns-resize"],[0.5,1,"ns-resize"],[1,0,"nesw-resize"],[1,0.5,"ew-resize"],[1,1,"nwse-resize"]],"rotate":true},"style":{"fill":"#fdf6e7","stroke":"#fbad5a","fillOpacity":1,"lineWidth":1,"lineDash":[]},"x":402.5,"y":31,"size":[40,40]}},{"documentation":"","id":"apply","name":"","properties":null,"type":"apply","uname":"","user":"","model":{"id":"apply","shape":"apply","label":"","labelCfg":{"position":"center","style":{"fontSize":12}},"width":80,"height":40,"minWidth":20,"minHeight":20,"anchorPoints":[[0.5,0],[0.5,1],[0,0.5],[1,0.5]],"shapeControl":{"controllers":[[0,0,"nwse-resize"],[0,0.5,"ew-resize"],[0,1,"nesw-resize"],[0.5,0,"ns-resize"],[0.5,1,"ns-resize"],[1,0,"nesw-resize"],[1,0.5,"ew-resize"],[1,1,"nwse-resize"]],"rotate":true},"style":{"fill":"#e7feeb","stroke":"#9efeae","fillOpacity":1,"lineWidth":1,"lineDash":[]},"x":402.5,"y":132,"size":[80,40]}},{"documentation":"","id":"task_g30","name":"上级审批","properties":null,"type":"task","uname":"","user":"","model":{"id":"task_g30","shape":"task","label":"","labelCfg":{"position":"center","style":{"fontSize":12}},"width":80,"height":40,"minWidth":20,"minHeight":20,"anchorPoints":[[0.5,0],[0.5,1],[0,0.5],[1,0.5]],"shapeControl":{"controllers":[[0,0,"nwse-resize"],[0,0.5,"ew-resize"],[0,1,"nesw-resize"],[0.5,0,"ns-resize"],[0.5,1,"ns-resize"],[1,0,"nesw-resize"],[1,0.5,"ew-resize"],[1,1,"nwse-resize"]],"rotate":true},"style":{"fill":"#e7f7fe","stroke":"#9ed2fe","fillOpacity":1,"lineWidth":1,"lineDash":[]},"x":402.5,"y":236,"size":[80,40]}},{"documentation":"","id":"end","name":"结束","properties":null,"type":"end","uname":"","user":"","model":{"id":"end","shape":"end","label":"","labelCfg":{"position":"center","style":{"fontSize":12}},"width":40,"height":40,"minWidth":20,"minHeight":20,"anchorPoints":[[0.5,0],[0.5,1],[0,0.5],[1,0.5]],"shapeControl":{"controllers":[[0,0,"nwse-resize"],[0,0.5,"ew-resize"],[0,1,"nesw-resize"],[0.5,0,"ns-resize"],[0.5,1,"ns-resize"],[1,0,"nesw-resize"],[1,0.5,"ew-resize"],[1,1,"nwse-resize"]],"rotate":true},"style":{"fill":"#fce6e9","stroke":"#f46369","fillOpacity":1,"lineWidth":1,"lineDash":[]},"x":402.5,"y":344,"size":[40,40]}}],
    "lines":[{"conditionType":"","from":"start","id":"g46","name":"","properties":null,"to":"apply","type":"","model":{"id":"g46","source":"start","sourceAnchor":1,"target":"apply","label":"","labelCfg":{"position":"center","style":{"fontSize":16,"stroke":"#000000"}},"lineAppendWidth":20,"attrs":{"start":"start","end":"apply"},"style":{"stroke":"#999999","lineWidth":1,"lineDash":[]},"shape":"x-line","startArrow":false,"endArrow":true,"startPoint":{"x":402.5,"y":51.5,"index":1},"endPoint":{"x":402.5,"y":111.5,"index":1},"targetAnchor":1}},{"conditionType":"","from":"apply","id":"g47","name":"","properties":null,"to":"task_g30","type":"","model":{"id":"g47","source":"apply","sourceAnchor":3,"target":"task_g30","label":"","labelCfg":{"position":"center","style":{"fontSize":16,"stroke":"#000000"}},"lineAppendWidth":20,"attrs":{"start":"apply","end":"task_g30"},"style":{"stroke":"#999999","lineWidth":1,"lineDash":[]},"shape":"x-line","startArrow":false,"endArrow":true,"startPoint":{"x":402.5,"y":152.5,"index":3},"endPoint":{"x":402.5,"y":256.5,"index":1},"targetAnchor":1}},{"conditionType":"","from":"task_g30","id":"g2","name":"","properties":null,"to":"end","type":"","model":{"id":"g2","source":"task_g30","sourceAnchor":1,"target":"end","label":"","labelCfg":{"position":"center","style":{"fontSize":16,"stroke":"#000000"}},"lineAppendWidth":20,"attrs":{"start":"task_g30","end":"end"},"style":{"stroke":"#999999","lineWidth":1,"lineDash":[]},"shape":"x-line","startArrow":false,"endArrow":true,"startPoint":{"x":402.5,"y":256.5,"index":1},"endPoint":{"x":402.5,"y":323.5,"index":0},"targetAnchor":0}}]
}

let dingform = {
    recharge: ['поставщик облачных услуг', 'цель пополнения', 'ожидаемое время пополнения', 'номер облачного счета пополнения', 'ожидаемая сумма пополнения', 'примечания'],
    budget: ['использовать', 'виды', 'расчетное время использования', 'детали бюджета', 'общий бюджет'],
    transfer: ['Поставщик облачных услуг', 'Заказчик по контракту', 'Номер облачного счета платящей стороны', 'Номер облачного счета платящей сторон', 'Предварительно запланированная дата перевода', 'Предварительно запланированная сумма перевода', 'Ориентировочная сумма возврата', 'Примечания ','Вложение размещения'],
    invoice: ['облачная платформа', 'тип счета-фактуры', 'тип выдачи', 'тип счета-фактуры', 'характер счета-фактуры', 'тип клиента', 'заказчик-фактура', 'сумма счета-фактуры', 'время выставления счета', ' Заголовок счета »,« имя получателя','номер телефона получателя ','адрес получения','примечания к счету ','вложение'],
    соглашение: ['номер контракта', 'заказчик контракта', 'тип контракта', 'срок подписи', 'крайний срок платежа', 'крайний срок счета', 'скидка', 'приложение', 'детали контракта']
    }
let dingdingFormData = {};
for(let i in dingform){
	dingdingFormData[i]=dingform[i].map((item,index)=>{
		var sIndex = index+1;
    	return {
            "componentName": "TextField",
            "type": "text",
            "props": {
                "placeholder": "welcome",
                "label": item,
                "id": "TextField-form"+Array(5-(sIndex+'').length).join('0')+sIndex,
                "required": false
            }
        }
    })
}
export let dingdingForm = dingdingFormData;